### ISSUE TITLE
dossier database

### ISSUE THREAD

**Issue by edupellaux** [lilianafss/EasyGame#4]
Vous devriez avoir à la racine de votre site un dossier ``` database ``` qui contient la **structure** de votre base de données (sans valeur, excepté un utilisateur admin de base si pertinent)

Dans ce fichier devrait se trouver un fichier avec la structure initiale de la base de données, puis ensuite à chaque modification devrait correspondre un nouveau fichier. En préfixant des fichiers avec la date, il serait facilement possible pour tout nouvel arrivant dans l'équipe d'avoir une base de donnée propre et à jour par rapport au reste de l'équipe.

Exemple : 

* 20220301_structure_initiale.sql --> contient la structure initiale
* 20220304_ajout_table_panier.sql --> contient la structure (create table) d'une nouvelle table
* 20220402_ajout_date_naissance_utilisateurs.sql --> ajoute la date de naissance dans la table utilisateur (alter table)

**Comment by LethalDarkLight** [comment]
La database était partagé sur le drive et à chaque modification nous avons supprimé l'ancienne version.
donc nous n'avons plus la version initial.

**Comment by lilianafss** [comment]
email: admin@gmail.com
password : Super2022
